-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

FROM debian:bookworm

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y apache2 vim less tree html2text procps sudo w3m
RUN apt-get install -y dumb-init curl iproute2 mariadb-client openssh-server
RUN apt-get install -y iputils-ping net-tools inotify-tools 

RUN a2enmod proxy_http  rewrite cgi
COPY 000-default.conf /etc/apache2/sites-available/

COPY myinit.sh /usr/bin

ENTRYPOINT ["/usr/bin/dumb-init","--"]
CMD ["/usr/bin/myinit.sh"]
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEFnLEynqq8h79HVgr1NADxTXbmY4FAmQQJY0ACgkQ1NADxTXb
mY6gig/+NogLL2y80+OM/Ns2cDfoqhp52Uu5lRmQCF5yJ0LCzCOA1KhrAF2d+FI1
MuO5yNt18J3DZMo0l8fVx4bP1j8tJBKmHlQiCot+bA0bb2nJ6qY2vq64oQasaU+K
BvIJd8L+ZUWqHaQpgtG6p26MHfRXV1Kk0G7lt8kBET2lCkOv1Uw8FhQGzv2QJcAg
A8koZbqw1sfoa+U6bUBjevH90TiOBXDJ19W5E6SaA05O7dTk7WkzHMFuBs7OpU10
guTp2jdI0coNEKti+FRDvSEQWMXoVtsLUB7aOg0Jd8YqNioDAnwRC3nn0p1ACKRB
w0E4+qD3+VzlvLwNDm1wA1iVnB6t/h0tCzxyf+gDgtnpsh2PJdWZEWteN3A+MkbU
WD0Ms1kXNFYPFSk1eAkuG2/ZuQwVvF8N4iNi/xPpuudA/1+DrApnM4nE0P1v7VkI
XdOzrERpDx2JVAs7q8Fkbg8d/i50y8wVmQFe80Fhzn1h9Bic8+gi7i1WZlOsd31j
KVA79AD5IyuLBH0oNvr89vwYqEG1fslUxmBoH/UEZ1TNuZi1leyy2lbcBxrTjt/h
0cJPD5qLDkf8+JiLogzCxkE1k73DakITRE1k9CgcIrfi9hl13gw3+E8cUnXFh4vA
b+MgVctWEygFgO1RDqJO2Q5J867v16M7iRs8GiSw5+yG2uFP3ig=
=zp0F
-----END PGP SIGNATURE-----
